### ISSUE TITLE
[P1] Facebook app wrong name and missing information

### ISSUE THREAD

**Issue by joelcloralt** [InstaJobs/webapp#7]
Our Facebook app doesn't have a picture and the name is incorrect. Our company name is not "Insta Job" it's "Instajobs"

<img width="500" alt="screenshot 2015-09-06 11 58 17" src="https://cloud.githubusercontent.com/assets/881780/9706084/b6543384-548e-11e5-95dc-5c1da0056237.png">

**Comment by ghost** [comment]
@joelcloralt i have added you as admin. you fix this.

**Comment by joelcloralt** [comment]
I have added the missing image. The name is under review by Facebook because they don't allow apps with "insta" in the names without review.

**Comment by codelion** [comment]
@joelcloralt I guess this is fixed now, if so we can close this issue?

**Comment by joelcloralt** [comment]
@codelion not yet. Facebook responded saying they will evaluate the request and get back to me but I'm still waiting.
